In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.0890, 0.9760, 0.5566],
        [0.8060, 0.9675, 0.2533],
        [0.1089, 0.6627, 0.9798],
        [0.9724, 0.0921, 0.0767],
        [0.3389, 0.9685, 0.7047]])


In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
import torch
import numpy as np

In [5]:
data = [[1, 2], [3, 4]]
x_data  = torch.tensor(data)
x_np = torch.tensor(np.array(data))

In [6]:
ones = torch.ones_like(x_data)
print(ones)

tensor([[1, 1],
        [1, 1]])


In [8]:
print(ones.shape, ones.dtype, ones.device)
ones = ones.to("cuda")
print(ones.device)

torch.Size([2, 2]) torch.int64 cpu
cuda:0


In [12]:
a = torch.zeros((2,2))
b = torch.ones((2,2))
c = torch.cat([a,b],dim=0)
print(c.shape)

torch.Size([4, 2])


In [13]:
a = torch.zeros((2,2))
b = torch.ones((2,2))
c = torch.cat([a,b],dim=1)
print(c.shape)

torch.Size([2, 4])


In [21]:
# Basic mathematical operations on tensors.
a = torch.ones((3,3))
b = torch.rand((3,3))

c = torch.mul(a, b)
print(c)

d  = torch.matmul(a, b)
print(d)

e  = d.sum()
print(e)

f = d.numpy()
print(f)

g = torch.from_numpy(f)
print(g)

tensor([[0.4806, 0.1873, 0.7259],
        [0.9649, 0.3019, 0.1389],
        [0.5287, 0.9692, 0.7695]])
tensor([[1.9742, 1.4583, 1.6343],
        [1.9742, 1.4583, 1.6343],
        [1.9742, 1.4583, 1.6343]])
tensor(15.2005)
[[1.9741615 1.4583478 1.6343124]
 [1.9741615 1.4583478 1.6343124]
 [1.9741615 1.4583478 1.6343124]]
tensor([[1.9742, 1.4583, 1.6343],
        [1.9742, 1.4583, 1.6343],
        [1.9742, 1.4583, 1.6343]])
